# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from canvasLabel import MyLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 231, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nextimgbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.nextimgbutton.setObjectName("nextimgbutton")
        self.gridLayout.addWidget(self.nextimgbutton, 1, 1, 1, 1)
        self.openimg = QtWidgets.QPushButton(self.layoutWidget)
        self.openimg.setObjectName("openimg")
        self.gridLayout.addWidget(self.openimg, 0, 1, 1, 1)
        self.openfolder = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.openfolder.setFont(font)
        self.openfolder.setObjectName("openfolder")
        self.gridLayout.addWidget(self.openfolder, 0, 0, 1, 1)
        self.preimgbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.preimgbutton.setObjectName("preimgbutton")
        self.gridLayout.addWidget(self.preimgbutton, 1, 0, 1, 1)
        self.markgood = QtWidgets.QPushButton(self.layoutWidget)
        self.markgood.setObjectName("markgood")
        self.gridLayout.addWidget(self.markgood, 2, 0, 1, 1)
        self.markbad = QtWidgets.QPushButton(self.layoutWidget)
        self.markbad.setObjectName("markbad")
        self.gridLayout.addWidget(self.markbad, 2, 1, 1, 1)
        self.showimg = MyLabel(self.centralwidget)
        self.showimg.setGeometry(QtCore.QRect(290, 30, 471, 501))
        self.showimg.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.showimg.setMouseTracking(False)
        self.showimg.setObjectName("showimg")
        self.imglist = QtWidgets.QListView(self.centralwidget)
        self.imglist.setGeometry(QtCore.QRect(31, 275, 111, 255))
        self.imglist.setObjectName("imglist")
        self.labellist = QtWidgets.QListView(self.centralwidget)
        self.labellist.setGeometry(QtCore.QRect(150, 319, 112, 211))
        self.labellist.setObjectName("labellist")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 251, 61, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 251, 81, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.labelname = QtWidgets.QLineEdit(self.centralwidget)
        self.labelname.setGeometry(QtCore.QRect(150, 280, 111, 26))
        self.labelname.setObjectName("labelname")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 131, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "imgManger"))
        self.nextimgbutton.setText(_translate("MainWindow", "Next Img"))
        self.openimg.setText(_translate("MainWindow", "Open Img"))
        self.openfolder.setText(_translate("MainWindow", "Open Folder"))
        self.preimgbutton.setText(_translate("MainWindow", "Pre Img"))
        self.markgood.setText(_translate("MainWindow", "Mark as Good"))
        self.markbad.setText(_translate("MainWindow", "Mark as Bad"))
        self.showimg.setText(_translate("MainWindow", "show img"))
        self.label_2.setText(_translate("MainWindow", "Logo List"))
        self.label_3.setText(_translate("MainWindow", "Label List"))
        self.label.setText(_translate("MainWindow", "Welcome to imgManger"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit Application"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
